[package]
name = "peviewer-rs"
version = "0.1.0"
edition = "2024"

[lints.rust]
unused = "allow"

[lib]
name = "pe"
path = "src/lib/lib.rs"

[[bin]]
name = "peviewer-gui"
path = "src/gui/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
comfy-table = "7"
eframe = "0.29"
rfd = "0.15"

[dev-dependencies]
tempfile = "3"
